# Generated by Django 4.2.7 on 2023-12-09 07:19

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tester_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('type', models.CharField(choices=[('TEST', 'Тест'), ('INTERPRETER', 'Интерпретатор')], default='TEST', max_length=15)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=tester_app.models.slugify_value, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default='2023-12-09 10:19:22')),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester_app.testing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField(max_length=150)),
                ('correct_answer', models.TextField(max_length=150)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester_app.testing')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester_app.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tester_app.result')),
            ],
        ),
    ]
