# Generated by Django 4.2.7 on 2023-12-08 12:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
