# Generated by Django 4.2.7 on 2023-12-08 15:55

import autoslug.fields
from django.db import migrations
import tester_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tester_app', '0002_testing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=tester_app.models.slugify_value, unique=True),
        ),
    ]
