# Generated by Django 4.2.7 on 2023-12-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester_app', '0003_alter_testing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
