# Generated by Django 4.2.7 on 2023-12-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester_app', '0004_answer_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='test_id',
            new_name='test',
        ),
    ]
