# Generated by Django 4.2.7 on 2023-12-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester_app', '0005_rename_question_id_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='text_question',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testing',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testing',
            name='type',
            field=models.CharField(choices=[('TEST', 'Тест'), ('INTERPRETER', 'Интерпретатор')], default='TEST', max_length=15),
        ),
    ]
