# Generated by Django 4.2.7 on 2023-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester_app', '0006_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='datetime',
            field=models.DateTimeField(default='2023-12-08 22:30:15'),
        ),
    ]
